baseURL    = 'https://<user>.github.io/hugo-class/'
languageCode = 'en-us'
title        = 'Taeyoung Lee'
theme        = 'PaperMod'

[params]
  author      = 'Taeyoung Lee'
  ShowReadingTime = false
  ShowBreadCrumbs = false
  disableScrollToTop = false

[menu]
  [[menu.main]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/taeoldlee"
    weight     = 10
  [[menu.main]]
    identifier = "linkedin"
    name       = "LinkedIn"
    url        = "https://linkedin.com/in/taeyoung-lee"
    weight     = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      attribute = true    

      
[caches]
  [caches.images]
    dir = ':cacheDir/images'